src/main/java/com/realdolmen/bean/DateTimeBean.java
package com.realdolmen.bean;

/**
 * Created by RCCBH67 on 13/09/2018.
 */
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.io.Serializable;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Map.Entry;

import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.inject.Named;
import javax.script.ScriptEngine;
import javax.script.ScriptEngineManager;
import javax.script.ScriptException;

import net.bootsfaces.utils.BsfUtils;
import net.bootsfaces.utils.LocaleUtils;

/**
 *
 * @author TheCoder4eu
 */
@Named
@RequestScoped
public class DateTimeBean implements Serializable {
    private static final long serialVersionUID = -7642332089180105956L;

    private boolean modeInline = false;

    private boolean sideBySide = false;

    private boolean showTime = true;

    private boolean showDate = true;

    private boolean showIcon = true;

    private boolean iconLeft = false;

    private boolean allowInputToggle = false;

    private boolean useCurrent = true;

    private String locale = Locale.getDefault().getLanguage();

    private String momentJSFormatString = null;

    private String javaFormatString = null;

    private static ScriptEngine scriptEngine;

    private static List<String> locales = new ArrayList<String>();

    private static final Comparator<Object> FORMAT_COMPARATOR = new Comparator<Object>() {

        @Override
        public int compare(Object o1, Object o2) {
            String k1 = (String) ((Entry) o1).getKey();
            String k2 = (String) ((Entry) o2).getKey();
            int result = k1.substring(0, 1).toUpperCase().compareTo(k2.substring(0, 1).toUpperCase());
            if (result == 0) {
                result = k1.substring(0, 1).compareTo(k2.substring(0, 1));
            }
            if (result == 0) {
                result = k1.compareTo(k2);
            }
            return result;
        }
    };

    private static final HashMap<String, String> momentToJava = new HashMap<String, String>() {
        {
            put("d", " (day in week - 0=Sunday, 6=Saturday");
            put("D", "d (day in month - one or two digits)");
            put("DD", "dd (day in month - two digits)");
            put("Do", "(day of month with ordinal)");
            put("Y", "(year - any number of digits and sign");
            put("YY", "yy (year - two digits)");
            put("YYYY", "yyyy (year - all digits)");
            put("a", "(am or pm)");
            put("A", "a (AM or PM)");
            put("M", "M (month in year - two digits, 01..12)");
            put("MM", "MM (month in year - two digits, 01..12)");
            put("MMM", "MMM (month in year - short text)");
            put("MMMM", "MMMM (month in year - full text)");
            put("h", "h (hour - one or two digits, 12 hours, 1..12)");
            put("hh", "hh (hour - two or two digits, 12 hours, 01..12)");
            put("H", "H (hour - one or two digits, 24 hours, 0..23)");
            put("HH", "HH (hour - two digits, 24 hours, 00..23)");
            put("k", "k (hour - one or two digits, 24 hours, 1..24)");
            put("kk", "kk (hour - two digits, 24 hours, 01..24)");
            put("m", "m (minutes - one or two digits)");
            put("mm", "mm (minutes - two digits)");
            put("s", "s (seconds - one or two digits)");
            put("ss", "ss (second - two digits)");
            put("S", "S (fractional seconds - 0...999");
            put("SS", "SS (fractional seconds - 00...999");
            put("SSS", "SSS (fractional seconds - 000...999");
            put("ddd", "E (day name - short)");
            put("dddd", "EEEE (day name - full)");
            put("DDD", "D (day in year)");
            put("DDDD", "DDD (day in year)");
            put("W", "w (week in year - one or two digits, 1..53)");
            put("WW", "ww (week in year - two digits, 01..53)");
            put("w", "(locale week in year - one or two digits, 1..53)");
            put("ww", "(locale week in year - two digits, 01..53)");
            put("ZZ", "ZZ (offset from UTC)");
            put("Z", "XXX (offset from UTC)");
            put("E", "u (ISO day of week - 1..7)");
            put("e", "(Locale day of week - 0..6)");
            put("Q", "(quarter in year - 1..4");
            put("X", "(UNIX timestamp)");
            put("x", "(UNIX timestamp - milliseconds)");
            put("[", "' (escape character)");
            put("]", "' (escape character)");
        }
    };

    @SuppressWarnings("serial")
    public static final HashMap<String, String> javaToMoment = new HashMap<String, String>() {
        {
            put("d", "D (day in month - one or two digits)");
            put("dd", "DD (day in month - two digits)");
            put("D", "DDD (day in year - one to three digits)");
            put("DD", "(day in year- two or three digits)");
            put("DDD", "DDDD (day in year- three digits)");
            put("F", "(day of week in month)");
            put("y", "YYYY (year - every digit)");
            put("yy", "YY (year - two digits)");
            put("yyy", "YYYY (year - three digits)");
            put("yyyy", "YYYY (year - every digit)");
            put("Y", "(week year - two digits)");
            put("YY", "gg (week year - two digits)");
            put("YYY", "(week year - three digits)");
            put("YYYY", "gggg (week year - all digits)");
            put("a", "A (AM or PM)");
            put("G", "(era - AD or BC)");
            put("M", "M (month in year - two digits, 1..12)");
            put("MM", "MM (month in year - two digits, 01..12)");
            put("MMM", "MMM (month in year - short text)");
            put("MMMM", "MMMM  (month in year - full text)");
            put("h", "h (hour - one or two digits, 12 hours, 1..12)");
            put("hh", "hh (hour - two digits, 12 hours, 01..12)");
            put("H", "H  (hour - one or two digits, 24 hours, 0..23)");
            put("HH", "HH (hour - two digits, 24 hours, 00..23)");
            put("k", "k (hour - one or two digits, 12 hours, 1..24)");
            put("kk", "kk (hour - two digits, 24 hours, 01..24)");
            put("K", "(hour - one or two digits, 12 hours, 0..11)");
            put("KK", "(hour - two digits, 12 hours, 00..11)");
            put("m", "m (minutes - one or two digits)");
            put("mm", "mm (minutes - two digits)");
            put("s", "s (seconds- one or two digits)");
            put("ss", "ss (seconds - two digits)");
            put("S", "S (millisecond)");
            put("SS", "SS  (millisecond)");
            put("SSS", "SSS  (millisecond)");
            put("E", "ddd (day name in week - short)");
            put("EE", "ddd  (day name in week - short)");
            put("EEE", "ddd  (day name in week - short)");
            put("EEEE", "dddd  (day name in week - full)");
            put("w", "W (week in year - one or two digits)");
            put("ww", "WW (week in year - two digits, zero-padded)");
            put("W", "(week in month - one or two digits)");
            put("WW", "(week in month - two digits, zero-padded)");
            put("z", "(General time zone)");
            put("zz", "(General time zone)");
            put("zzz", "(General time zone)");
            put("zzzz", "(General time zone)");
            put("Z", "ZZ (RFC 822 time zone)");
            put("X", "(ISO 8601 time zone -  - hours only)");
            put("XX", "ZZ (ISO 8601 time zone - short)");
            put("XXX", "Z (ISO 8601 time zone - long)");
            put("u", "E (day number of week - 1=Monday, 7=Sunday)");
            put("'", "[] (escape character)");
        }
    };

    static Map<Integer, String> predefinedJavaFormats = new HashMap<Integer, String>();
    static List<String> predefinedMomentjsFormats = new ArrayList<String>();

    static {
        for (Locale locale : DateFormat.getAvailableLocales()) {
            String l = locale.getLanguage();
            if (!locales.contains(l))
                locales.add(l);
            Collections.sort(locales);
        }
        predefinedJavaFormats.put(SimpleDateFormat.SHORT, "SimpleDateFormat.SHORT");
        predefinedJavaFormats.put(SimpleDateFormat.MEDIUM, "SimpleDateFormat.MEDIUM");
        predefinedJavaFormats.put(SimpleDateFormat.LONG, "SimpleDateFormat.LONG");
        predefinedJavaFormats.put(SimpleDateFormat.FULL, "SimpleDateFormat.FULL");

        predefinedMomentjsFormats.add("LT");
        predefinedMomentjsFormats.add("LTS");
        predefinedMomentjsFormats.add("L");
        predefinedMomentjsFormats.add("l");
        predefinedMomentjsFormats.add("LL");
        predefinedMomentjsFormats.add("ll");
        predefinedMomentjsFormats.add("LLL");
        predefinedMomentjsFormats.add("lll");
        predefinedMomentjsFormats.add("LLLL");
        predefinedMomentjsFormats.add("llll");

        loadMomentSource();

    }

    private static void loadMomentSource() {
        InputStream is = Thread.currentThread().getContextClassLoader()
                .getResourceAsStream("/META-INF/resources/bsf/js/moment.min.js");
        Reader reader = new InputStreamReader(is);
        ScriptEngineManager manager = new ScriptEngineManager();
        scriptEngine = manager.getEngineByName("JavaScript");
        try {
            scriptEngine.eval(reader);
        } catch (ScriptException e) {
            e.printStackTrace();
        }
    }

    public String formatDateAsMomentJSDate() {
        if (momentJSFormatString == null || momentJSFormatString.equals("")) {
            return "";
        }
        try {
            String variableName = "z" + (new Date()).getTime();

src/main/java/com/realdolmen/bean/GrowlBean.java
package com.realdolmen.bean;

import javax.enterprise.context.RequestScoped;
import javax.enterprise.context.SessionScoped;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import java.io.Serializable;
import java.util.ResourceBundle;

/**
 * Created by RCCBH67 on 12/09/2018.
 */
@Named
@SessionScoped
public class GrowlBean implements Serializable {
    @Inject
    private LanguageSwitcher languageSwitcher;

    private FacesMessage message = new FacesMessage();

    public void showInformationGrowl(String detail, String summary){
        this.message.setDetail(detail);
        this.message.setSummary(summary);
        this.message.setSeverity(FacesMessage.SEVERITY_INFO);
        FacesContext.getCurrentInstance().addMessage(null, this.message);
    }

    public void showFatalGrowl(String detail, String summary){
        this.message.setDetail(detail);
        this.message.setSummary(summary);
        this.message.setSeverity(FacesMessage.SEVERITY_FATAL);
        FacesContext.getCurrentInstance().addMessage(null, this.message);
    }

    public void showErrorGrowl(String detail, String summary){
        this.message.setDetail(detail);
        this.message.setSummary(summary);
        this.message.setSeverity(FacesMessage.SEVERITY_ERROR);
        FacesContext.getCurrentInstance().addMessage(null, this.message);
    }

    public void showWarningGrowl(String detail, String summary){
        this.message.setDetail(detail);
        this.message.setSummary(summary);
        this.message.setSeverity(FacesMessage.SEVERITY_WARN);
        FacesContext.getCurrentInstance().addMessage(null, this.message);
    }
}

src/main/java/com/realdolmen/bean/UserBean.java
package com.realdolmen.bean;

import com.realdolmen.domain.User;
import com.realdolmen.dto.UserDTO;


import javax.enterprise.context.SessionScoped;
import javax.inject.Named;
import java.io.Serializable;

/**
 * Created by RCCBH67 on 11/09/2018.
 */
@Named
@SessionScoped
public class UserBean implements Serializable {
    private User user = new UserDTO();

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public UserBean() {
        user = new UserDTO();
    }

    public Boolean isLoggedIn() {
        return this.isCustomer() | this.isEmployee() | this.isPartner();
    }

    public Boolean isCustomer(){
        return this.user.getClass().getSimpleName().equals("Customer");
    }

    public Boolean isEmployee(){
        return this.user.getClass().getSimpleName().equals("Employee");
    }

    public Boolean isPartner(){
        return this.user.getClass().getSimpleName().equals("Partner");
    }
}

src/main/java/com/realdolmen/domain/BusinessClass.java
package com.realdolmen.domain;

import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

@DiscriminatorValue(value = "BUSINESS_CLASS")
@Entity
public class BusinessClass extends FlightClass {

	public String getClassName()
	{
		return "Business Class";
	}
}

src/main/java/com/realdolmen/domain/Customer.java
package com.realdolmen.domain;


import javax.persistence.DiscriminatorValue;
import javax.persistence.Entity;

@DiscriminatorValue(value = "CUSTOMER")
@Entity
public class Customer extends User {
}

src/main/java/com/realdolmen/domain/Endorsement.java
package com.realdolmen.domain;

public class Endorsement extends PaymentMethod {
}

src/main/java/com/realdolmen/domain/Flight.java
package com.realdolmen.domain;

import javax.persistence.*;
import javax.validation.constraints.Future;
import javax.validation.constraints.NotNull;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


@Entity
public class Flight implements Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Long id;

	@NotNull(message = "{Field_Not_Selected}")
	private LocalDateTime departureTime;
	private LocalTime duration;
	private Boolean enabled;
	@OneToMany(mappedBy = "flight",fetch = FetchType.EAGER)
	private List<Booking> bookingsList;
	@OneToMany(fetch = FetchType.EAGER, cascade = CascadeType.ALL)
	@JoinColumn(name = "flight_id")
	private List<Discount> discountList = new ArrayList<Discount>();
	@OneToOne(fetch = FetchType.EAGER,cascade = CascadeType.ALL)
	@NotNull(message = "{Field_Not_Selected}")
	private Location departure;
	@NotNull(message = "{Field_Not_Selected}")
	@OneToOne(fetch = FetchType.EAGER,cascade = CascadeType.ALL)
	private Location destination;
	@OneToOne
	private Partner partner;
	@OneToOne(fetch = FetchType.EAGER,targetEntity = FlightClass.class, cascade = CascadeType.ALL)
	private FirstClass firstClass = new FirstClass();
	@OneToOne(fetch = FetchType.EAGER,targetEntity = FlightClass.class, cascade = CascadeType.ALL)
	private BusinessClass businessClass = new BusinessClass();
	@OneToOne(fetch = FetchType.EAGER,targetEntity = FlightClass.class, cascade = CascadeType.ALL)
	private EconomyClass economyClass = new EconomyClass();

	@Transient
	@Future(message = "{Date_Future}")
	private Date departureTimeAsDate;

	@Transient
	private String durationTimeAsString;

	public FirstClass getFirstClass() {
		return firstClass;
	}

	public void setFirstClass(FirstClass firstClass) {
		this.firstClass = firstClass;
	}

	public BusinessClass getBusinessClass() {
		return businessClass;
	}

	public void setBusinessClass(BusinessClass businessClass) {
		this.businessClass = businessClass;
	}

	public EconomyClass getEconomyClass() {
		return economyClass;
	}

	public void setEconomyClass(EconomyClass economyClass) {
		this.economyClass = economyClass;
	}

	public LocalTime getDuration() {
		return duration;
	}

	public void setDuration(LocalTime duration) {
		this.duration = duration;
	}

	public Boolean getEnabled() {
		return enabled;
	}

	public void setEnabled(Boolean enabled) {
		this.enabled = enabled;
	}

	public List<Booking> getBookingsList() {
		return bookingsList;
	}

	public void setBookingsList(List<Booking> bookingsList) {
		this.bookingsList = bookingsList;
	}

	public List<Discount> getDiscountList() {
		return discountList;
	}

	public void setDiscountList(List<Discount> discountList) {
		this.discountList = discountList;
	}

	public Location getDeparture() {
		return departure;
	}

	public void setDeparture(Location departure) {
		this.departure = departure;
	}

	public Location getDestination() {
		return destination;
	}

	public void setDestination(Location destination) {
		this.destination = destination;
	}

	public Partner getPartner() {
		return partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	public LocalDateTime getDepartureTime() {
		return departureTime;
	}

	public String getDepartureTimeAsString() {
		DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/YYYY");
		return this.departureTime != null ? this.departureTime.toLocalDate().format(formatter) + " - " + this.departureTime.toLocalTime() : "";
	}

	public void setDepartureTime(LocalDateTime departureTime) {
		this.departureTime = departureTime;
	}

	public Date getDepartureTimeAsDate() {
		return this.departureTimeAsDate != null ? this.departureTimeAsDate : new Date();
	}

	public void setDepartureTimeAsDate(Date departureTimeAsDate) {
		this.departureTimeAsDate = departureTimeAsDate;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getDurationTimeAsString() {
		return durationTimeAsString;
	}

	public void setDurationTimeAsString(String durationTimeAsString) {
		this.durationTimeAsString = durationTimeAsString;
	}
}

src/main/webapp/404.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core" xmlns:b="http://bootsfaces.net/ui">

<ui:composition template="/template.xhtml">
    <ui:define name="pageContent">
        <h:form>
        <div class="404">
               <div class="error-template">
                   <h1>#{msgs['404_Header']}</h1>
                   <h2>#{msgs['404_Content']}</h2>
                   <div class="error-details">
                       #{msgs['404_Details']}
                   </div>
                   <div class="error-actions">
                       <h:commandLink styleClass="btn btn-primary btn-lg" value="#{msgs['404_Home']}" action="#{navigationBean.navigateToHome(true)}">
                           <i class="glyphicon glyphicon-home"/>
                       </h:commandLink>
                   </div>
               </div>
           </div>
        </h:form>
</ui:define>
</ui:composition>

</html>

src/main/webapp/bookingSuccess.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:p="http://primefaces.org/ui" xml:lang="en" lang="en">
<ui:composition template="/template.xhtml">
    <ui:define name="pageContent">
        <h:outputText value="#{msgs['Success_Message']}"/>
        <h:form>
            <p:growl id="messages" showDetail="true" />
        </h:form>
    </ui:define>
</ui:composition>
</html>

src/main/webapp/confirmBooking.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html" xmlns:p="http://primefaces.org/ui"
      xml:lang="en" lang="en">
<ui:composition template="/template.xhtml">
    <ui:define name="pageContent">
        <h:form rendered="#{not empty bookingController.flight}">
            <p:growl id="messages" showDetail="true" />
            <h:panelGroup>
                <table class="table table-sm">
                    <tr>
                        <th scope="row">#{msgs['Home_Departure']}</th>
                        <td>
                            <h:outputText value="#{bookingController.flight.departure.airportName}"/>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">#{msgs['Home_Destination']}</th>
                        <td>
                            <h:outputText value="#{bookingController.flight.destination.airportName}"/>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">#{msgs['Details_DepartureTime']}</th>

                        <td>
                            <h:outputText value="#{bookingController.flight.departureTimeAsString}"/>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">#{msgs['Home_Duration']}</th>

                        <td>
                            <h:outputText value="#{bookingController.flight.duration}"/>
                        </td>
                    </tr>
                    <tr>
                        <th scope="row">#{msgs['Details_CompanyName']}</th>

                        <td>
                            <h:outputText value="#{bookingController.flight.partner.companyName}"/>
                        </td>
                    </tr>
                </table>
            </h:panelGroup>
            <br/>
            <h:panelGroup>
                <table class="table table-sm">
                    <tr>
                        <th scope="col">#{msgs['Details_Class']}</th>
                        <th scope="col">#{msgs['Details_AmountOfSeatsChosen']}</th>
                        <th scope="col">#{msgs['Details_Discount']}</th>
                        <th scope="col">#{msgs['Details_TotalPrice']}</th>
                        <th scope="col">#{msgs['Booking_PaymentMethod']}</th>
                    </tr>
                    <tr>
                        <th scope="row"><h:outputText value="#{bookingController.booking.travelingClass}"/></th>
                        <td>
                            <h:outputText value="#{bookingController.booking.amountOfSeats}"/>
                        </td>
                        <td>
                            <h:outputText value="#{bookingController.discountPercentage}"/>%
                        </td>
                        <td>
                            <h:outputText value="#{bookingController.booking.totalPrice}"/>
                        </td>
                        <td>
                            <h:outputText value="#{bookingController.paymentMethod}"/>
                        </td>
                    </tr>
                </table>
            </h:panelGroup>
            <h:panelGroup styleClass="pull-right">
                <h:commandButton styleClass="btn btn-primary" action="#{bookingController.goBackToDetail}"
                                 value="#{msgs['Booking_Back']}"/>
                &#160;
                <h:commandButton styleClass="btn btn-primary" action="#{bookingController.confirmBooking}"
                                 value="#{msgs['Booking_Book']}"/>
            </h:panelGroup>
        </h:form>
    </ui:define>
</ui:composition>
</html>

src/main/webapp/flightDetail.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html
        PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui" xml:lang="en" lang="en">
<ui:composition template="/template.xhtml">
    <ui:define name="pageContent">
        <f:metadata>
            <f:viewParam name="id" value="#{flightController.flight}"
                         converter="#{flightConverter}"
                         converterMessage="Unknown product, please use a link from within the system."
            />
        </f:metadata>

        <h:form rendered="#{not empty flightController.flight}">
            <table class="table table-sm">
                <tr>
                    <th scope="row">#{msgs['Home_Departure']}</th>
                    <td>
                        <h:outputText value="#{flightController.flight.departure.airportName}"/>
                    </td>
                </tr>
                <tr>
                    <th scope="row">#{msgs['Home_Destination']}</th>
                    <td>
                        <h:outputText value="#{flightController.flight.destination.airportName}"/>
                    </td>
                </tr>
                <tr>
                    <th scope="row">#{msgs['Details_DepartureTime']}</th>

                    <td>
                        <h:outputText value="#{flightController.flight.departureTimeAsString}"/>
                    </td>
                </tr>
                <tr>
                    <th scope="row">#{msgs['Home_Duration']}</th>
                    <td>
                        <h:outputText value="#{flightController.flight.duration}"/>
                    </td>
                </tr>
                <tr>
                    <th scope="row">#{msgs['Details_CompanyName']}</th>

                    <td>
                        <h:outputText value="#{flightController.flight.partner.companyName}"/>
                    </td>
                </tr>
            </table>
            <hr/>
            <table class="table table-sm">
                <tr>
                    <th scope="col"> #{msgs['Details_Class']}</th>
                    <th scope="col">#{msgs['Details_AmountOfSeats']}</th>
                    <th scope="col">#{msgs['Details_Price']}</th>
                    <th scope="col"></th>
                </tr>
                <tr>
                    <th scope="row">#{msgs['Details_FirstClassSeats']}</th>
                    <td>
                        <h:outputText value="#{flightController.flight.firstClass.amountOfSeats}"/>
                    </td>
                    <td>
                        <h:outputText
                                value="#{flightController.flight.firstClass.basePrice + flightController.flight.firstClass.profitMargin}"/>
                    </td>
                    <td>
                        <h:form>
                            <p:button outcome="booking" icon="ui-icon-cart">
                                <f:param name="flightId" value="#{flightController.flight.id}"/>
                                <f:param name="flightClass" value="firstClass"/>
                            </p:button>
                        </h:form>
                    </td>
                </tr>
                <tr>
                    <th scope="row">#{msgs['Details_BusinessClassSeats']}</th>
                    <td>
                        <h:outputText value="#{flightController.flight.businessClass.amountOfSeats}"/>
                    </td>
                    <td>
                        <h:outputText
                                value="#{flightController.flight.businessClass.basePrice + flightController.flight.businessClass.profitMargin}  "/>
                    </td>
                    <td>
                        <h:form>
                            <p:button outcome="booking" icon="ui-icon-cart">
                                <f:param name="flightId" value="#{flightController.flight.id}"/>
                                <f:param name="flightClass" value="businessClass"/>
                            </p:button>
                        </h:form>
                    </td>
                </tr>
                <tr>
                    <th scope="row">#{msgs['Details_EconomyClassSeats']}</th>
                    <td>
                        <h:outputText value="#{flightController.flight.economyClass.amountOfSeats}"/>
                    </td>
                    <td>
                        <h:outputText
                                value="#{flightController.flight.economyClass.basePrice + flightController.flight.economyClass.profitMargin}"/>
                    </td>
                    <td>
                        <h:form rendered="#{flightController.flight.economyClass.amountOfSeats > 0}">
                            <p:button outcome="booking" icon="ui-icon-cart">
                                <f:param name="flightId" value="#{flightController.flight.id}"/>
                                <f:param name="flightClass" value="economyClass"/>
                            </p:button>
                        </h:form>
                    </td>
                </tr>
            </table>
        </h:form>

    </ui:define>
</ui:composition>
</html>